version: '2'

services:
  service_php:
    build: docker/php
    tty: true
    labels:
      kompose.service.type: nodeport
    ports:
      - 9000:9000
    volumes:
      - ./app:/app

  service_nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

  service_postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
        - "5433:5432"
    expose:
      - 5433
    volumes:
      - ./app/var/data:/var/lib/postgresql/data

  service_puzzle_api:
    image: luwangel/15-puzzle-api
    command: go run main/main-server.go .
    ports:
      - "2000:2000"
