version: '2'

services:
  postgres:
      image: postgres:alpine
      restart: always
      ports:
        - "5432:5432"
  php:
    build: docker/php
    tty: true
    labels:
      kompose.service.type: nodeport
    ports:
      - 9000:9000
    volumes:
      - ./app:/app
  nginx:
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
         - ./app:/app
         - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
