index:
   path: /
   defaults: { _controller: 'App\Controller\HelloController::start' }

# app_controller:
#     path: /hello
#     controller: App\Controller\HelloController::start

# first, run composer req annotations
# controllers:
#    resource: ../src/Controller/
#    type: annotation
