index:
  path: /
  defaults: { _controller: 'App\Controller\MainController::start' }

game_new:
  path: /game
  defaults: { _controller: 'App\Controller\GameController::new' }

game:
  path: /game/{id}
  defaults: { _controller: 'App\Controller\GameController::play' }
  options:
    utf8: true

game_move:
  path: /game/{id}/move/{tile}
  defaults: { _controller: 'App\Controller\GameController::move' }
  options:
    utf8: true
