index:
  path: /
  defaults: { _controller: 'App\Controller\MainController::start' }

game_new:
  path: /game/new/{mode}
  defaults: { _controller: 'App\Controller\GameController::new' }

game:
  path: /game/{id}
  defaults: { _controller: 'App\Controller\GameController::play' }

game_join:
  path: /game/{id}/join
  defaults: { _controller: 'App\Controller\GameController::join' }

game_cancel:
  path: /game/{id}/cancel
  defaults: { _controller: 'App\Controller\GameController::cancel' }

game_move:
  path: /game/{id}/move/{tile}
  defaults: { _controller: 'App\Controller\GameController::move' }
