index:
  path: /
  defaults: { _controller: 'App\Controller\MainController::start' }

## GAME

game_new:
  path: /game/new/{mode}
  defaults: { _controller: 'App\Controller\GameController::new' }

game:
  path: /game/{id}
  defaults: { _controller: 'App\Controller\GameController::play' }

game_join:
  path: /game/{id}/join
  defaults: { _controller: 'App\Controller\GameController::join' }

game_cancel:
  path: /game/{id}/cancel
  defaults: { _controller: 'App\Controller\GameController::cancel' }

game_move:
  path: /game/{id}/move/{tile}
  defaults: { _controller: 'App\Controller\GameController::move' }

## API

api_game_new:
  path: /api/game
  defaults: { _controller: 'App\Controller\ApiController::new' }
  methods: [OPTIONS, POST]

api_game:
  path: /api/game/{id}
  defaults: { _controller: 'App\Controller\ApiController::game' }
  methods: [OPTIONS, GET]

api_game_cancel:
  path: /api/game/{id}
  defaults: { _controller: 'App\Controller\ApiController::cancel' }
  methods: [OPTIONS, DELETE]

api_game_join:
  path: /api/game/{id}/join
  defaults: { _controller: 'App\Controller\ApiController::join' }
  methods: [OPTIONS, POST]

api_game_move:
  path: /api/game/{id}/move/{tile}
  defaults: { _controller: 'App\Controller\ApiController::move' }
  methods: [OPTIONS, PUT]

api_games:
  path: /api/games/open
  defaults: { _controller: 'App\Controller\ApiController::games' }
  methods: [OPTIONS, GET]

api_suggest:
  path: /api/suggest
  defaults: { _controller: 'App\Controller\ApiController::suggest' }
  methods: [OPTIONS, POST]
